baseURL = "https://dave.nl/"
languageCode = "nl-nl"
title = "Dave.nl"
theme = "ink"

copyright = "© Dave van Hoorn"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	subtitle = "Digitaal ondernemen @dave.nl analoog noten branden @noten.nl"
	avatar = "/images/dave.png"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
mode = "auto" # "dark" or "auto"