baseURL = "https://dave.nl/"
languageCode = "nl-nl"
title = "Dave.nl"
theme = "ink"

copyright = "© Dave van Hoorn | yo@dave.nl | +31 (0)6 169 100 79"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	subtitle = "Online ondernemen op Dave.nl, offline ondernemen bij Noten.nl"
	avatar = "/images/dave.png"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
mode = "auto" # "dark" or "auto"