# Variables VERCEL_TOKEN, VERCEL_ORG_ID and VERCEL_PROJECT_ID can be found in Vercel

name: PR Source Code Check
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm
      - run: pnpm lint:strict

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm
      - run: pnpm typecheck

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm
      - run: pnpm format:check

  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm
      - run: pnpm test

  web-vitals:
    name: Run Web Vitals
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel env pull --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Lighthouse CI
        run: pnpm global add @lhci/cli@0.9.x

      - name: Install dependencies
        run: pnpm --prefer-offline

      - name: Build Next.js
        run: pnpm build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: lhci autorun
